"""Send a daily HTML report to mikekent389@gmail.com summarizing the run.

Reads:
  state/deals_<DATE>.json
  state/neighbor_changes_<DATE>.json
  state/cp_updates_<DATE>.json
  state/summaries_<DATE>.json
  run_log/latest_run.json

SMTP via Gmail. App password in env var GMAIL_APP_PASSWORD.
"""
from __future__ import annotations
import json
import os
import smtplib
import sys
from datetime import datetime, timezone
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
STATE_DIR = os.path.join(ROOT, "state")
LOG_DIR   = os.path.join(ROOT, "run_log")

DATE = datetime.now(timezone.utc).strftime("%Y%m%d")
DATE_HUMAN = datetime.now(timezone.utc).strftime("%Y-%m-%d")

EMAIL_TO   = os.environ.get("REPORT_EMAIL_TO", "mikekent389@gmail.com")
EMAIL_FROM = os.environ.get("REPORT_EMAIL_FROM", "mikekent389@gmail.com")
APP_PW     = os.environ.get("GMAIL_APP_PASSWORD")


def load(path):
    if not os.path.exists(path):
        return None
    with open(path, encoding="utf-8") as f:
        return json.load(f)


def render_html():
    pull = load(os.path.join(LOG_DIR, "latest_run.json")) or {}
    nc   = load(os.path.join(STATE_DIR, f"neighbor_changes_{DATE}.json")) or {}
    cp   = load(os.path.join(STATE_DIR, f"cp_updates_{DATE}.json")) or {}
    sm   = load(os.path.join(STATE_DIR, f"summaries_{DATE}.json")) or {}

    rows = []
    rows.append(f"<h2>BH Daily Enrichment — {DATE_HUMAN}</h2>")
    rows.append("<h3>Run summary</h3><ul>")
    rows.append(f"<li>Deals snapshot: {pull.get('deals_count', '?')}</li>")
    rows.append(f"<li>Notes snapshot deals: {pull.get('notes_deals_count', '?')}</li>")
    rows.append(f"<li>New neighbor flags: {nc.get('neighbor_change_count', 0)}</li>")
    rows.append(f"<li>Connected-Properties deals updated: {cp.get('updated', 0)}</li>")
    rows.append(f"<li>Summaries posted: {sm.get('summaries_posted', 0)}</li>")
    rows.append("</ul>")

    changes = (nc.get("changes") or [])[:50]
    if changes:
        rows.append("<h3>New neighbors detected today</h3><table border='1' cellpadding='4' cellspacing='0'><tr><th>New Deal</th><th>Block</th><th>Existing siblings</th><th>Title</th></tr>")
        for c in changes:
            rows.append(
                f"<tr><td><a href='https://bhinvestments.pipedrive.com/deal/{c['new_deal_id']}'>{c['new_deal_id']}</a></td>"
                f"<td>{c.get('block_key','')}</td>"
                f"<td>{', '.join(str(x) for x in c.get('existing_neighbor_deal_ids', []))}</td>"
                f"<td>{(c.get('new_deal_title') or '')[:120]}</td></tr>"
            )
        rows.append("</table>")

    errs = []
    for src in (pull, nc, cp, sm):
        for e in (src.get("errors") or []):
            errs.append(e)
    if errs:
        rows.append(f"<h3>Errors ({len(errs)})</h3><pre>{json.dumps(errs[:30], indent=2)[:5000]}</pre>")

    rows.append("<hr/><small>auto-generated by bh-enrichment GitHub Action</small>")
    return "\n".join(rows)


def main():
    if not APP_PW:
        print("ERROR: GMAIL_APP_PASSWORD env var missing", file=sys.stderr); sys.exit(2)

    body = render_html()
    msg = MIMEMultipart("alternative")
    msg["Subject"] = f"BH Daily Enrichment — {DATE_HUMAN}"
    msg["From"] = EMAIL_FROM
    msg["To"] = EMAIL_TO
    msg.attach(MIMEText(body, "html"))

    with smtplib.SMTP("smtp.gmail.com", 587, timeout=30) as s:
        s.starttls()
        s.login(EMAIL_FROM, APP_PW)
        s.sendmail(EMAIL_FROM, [EMAIL_TO], msg.as_string())
    print(f"sent to {EMAIL_TO}")


if __name__ == "__main__":
    main()
